language: node_js
node_js:
- 5.0.0
before_deploy:
- npm run demo
deploy:
  provider: heroku
  api_key:
    secure: N8mfjNi5OoC5WUjamDvoQkdVqI0/re7/jeGpWHf6IRbRxtOm3nky2WO0Hv3xaNOKCNf9h4Zu0wti3lOmlCnMvXynRTAwj8Fv09mYSgfw6AD8+U1iTOn9pWPEek/pRKKRn6cnSk1k12mId7DdFydbWqwXIZkbqY4Pl+u5+dluPdk=
  skip_cleanup: true
